### ISSUE TITLE
[API de Reportagens] Refazer archive de Notícias conforme novo layout aprovado

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#100]
O layout da nova archive de notícias está disponível na versão 1.0 das páginas do Figma. Segue um print para facilitar:

![image](https://user-images.githubusercontent.com/3427567/144048125-5a00c48f-7b2a-460f-99d6-f3068c94a8c7.png)

Seguem alguns comentários sobre a descrição da nova página:

- [x] Sidebars: manter apenas newsletter e colunistas de opinião.

- [x] Inserir campo de descrição na archive de notícias (logo abaixo o título Notícias), com os textos:
"Conteúdo sobre desmatamento na Amazônia, com curadoria diária de notícias, estudos, reportagens, colunas de opinião e boas iniciativas sobre desmatamento e conservação na região."
"Content on deforestation in the Amazon, with the curatorship of news stories, studies, special reports, opinion articles, and good initiatives, which aim at contributing to the preservation and ending deforestation in the region."

Observação: esse campo, neste momento, só poderá ser editado pelo código e não pelo painel. 

- [x] Inserir na archive de Notícias os botões com as categorias existentes em notícias. Funcionamento desses botões: ao clicar nesses botões, a página aberta será a da categoria (padrão do WP) com o acréscimo do campo de descrição de cada categoria. 

- [x] Nas páginas de resultados por categoria, por exemplo, "Opinião", também deve ter esse campo previsto de texto descritivo.
Observação: Esse campo de texto poderá ser editado pelo painel. Seguem abaixo os textos descritivos de cada página de categoria:

Na mídia
Curadoria diária de notícias, informações sobre estudos e pesquisas relacionados à questão do desmatamento. O conteúdo é produzido pela equipe do Instituto ClimaInfo especialmente para o PlenaMata.

Opinião
Artigos de opinião semanais escritos por uma rede de articulistas fixos e convidados. A visão de cientistas, especialistas em políticas públicas, cadeias de produção e comunidades atingidas pelo desmatamento.

Reportagens
Matérias, entrevistas e reportagens investigativas produzidas pelo InfoAmazonia sobre desmatamento especialmente para o PlenaMata.

Boas iniciativas
Perfis e entrevistas sobre iniciativas, tecnologias e bons exemplos de projetos pelo fim do desmatamento na Amazônia.

On the media
Daily curatorship of news, information on studies and research related to the issue of deforestation. The content is produced by the ClimaInfo Institute team especially for PlenaMata.

Opinion
Weekly opinion articles written by a network of regular and guest columnists. The vision of scientists, specialists in public policies, production chains and communities affected by deforestation.

Stories
Stories, interviews and investigative stories produced by InfoAmazonia on deforestation especially for PlenaMata.

Good initiatives
Profiles and interviews about initiatives, technologies and good examples of projects to end deforestation in the Amazon.

**Comment by estercmandrade** [comment]
A descrição da Archive e das Categorias foram adicionadas no ambiente de produção.
