### ISSUE TITLE
[Documentação] Adicionar documentação sobre as atualizações de glossário e notícias

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#101]
- [x] Como incluir os termos de glossário nos posts
- [x] Como editar o texto de descrição da archive de Notícias
- [x] Como editar o texto de descrição das páginas de categorias de Notícias
- [ ] Como editar o nome das categorias (como adicionar, remover, editar aqueles botões de categorias)

**Comment by estercmandrade** [comment]
Sobre o último item, os botões das categorias são adicionados automaticamente.
