### ISSUE TITLE
[API de Reportagens] Inserir breadcrumb nas páginas de categorias de notícias, conforme layout

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#102]
![image](https://user-images.githubusercontent.com/3427567/144620410-c7e88b51-f91a-48ed-9ec8-a9b9f68576fd.png)

**Comment by leopiccionia** [comment]
Adicionei as breadcrumbs aos archives de categoria. É preciso adicioná-las também aos archives de tag?
