### ISSUE TITLE
[Boas iniciativas] Incluir sub-categorias e alterar a página da categoria conforme o layout aprovado

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#103]
[Boas Iniciativas] Foi definido que as subcategorias serão:

Academia
Comunidades
Monitoramento
Setor Público
Setor Privado
Sociedade Civil

Essas categorias não são exclusivas, isto é, um post de boas iniciativa pode estar em mais de uma subcategoria.

**Comment by leopiccionia** [comment]
Subi as atualizações e criei as categorias em dev.

**Comment by paularfurtado** [comment]
@leopiccionia elas não estão aparecendo aqui https://plenamata.hacklab.com.br/category/boas-iniciativas/ . Eu preciso fazer algo?
