### ISSUE TITLE
[Infra] Configuração do Cloudflare

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#104]
Tarefas anteriores à alterações do nameserver:

- [x] Revisar e realizar configurações no Cloudflare

Tarefas posteriores à alterações do nameserver:

- [x] Alterar o certificado SSL instalado no servidor por um gerado pelo Cloudflare

Email para acesso ao Cloudflare: plenamata@hacklab.com.br

Mensagem enviada pelo @bwstefano :

"Combinamos ontem com o Arapyaú de receber controle sobre o DNS. Para isso, eu configurei o Cloudflare e fiz uma inscrição ao Project Galileo, que dá a versão Business do Cloudflare de graça para sites jornalísticos, entre outros. Assim que o acesso for concedido, vou abrir o Cloudflare com vocês para que verifiquem as configurações e façam todos os ajustes antes que o nameserver seja alterado. Gostaria que me informassem quais e-mails devo convidar para acessar o Cloudflare e que incluíssem esta tarefa no pipeline da semana que vem.

Além de revisar as configurações no Cloudflare, será necessário alterar o certificado SSL instalado no servidor por um gerado pelo Cloudflare, o que é feito depois que o nameserver é alterado."

**Comment by bwstefano** [comment]
Enviei o convite de acesso para plenamata@hacklab.com.br. Ainda estou aguardando resposta do Project Galileo para prosseguir com a mudança do nameserver.

**Comment by willowmagrini** [comment]
Já estamos com a conta configurada e ativamos o certificado do cloudflare.

**Comment by bwstefano** [comment]
Fomos aprovados no Project Galileo e as configurações extras a que recebemos acesso, da versão Business, já estão disponíveis.
