### ISSUE TITLE
[Layout] Redefinir as cores que marcam os diferentes tipos de território no mapa

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#105]
Sugestão de cores feita pela @luizapeixe  precisa ser refeita no base layer do PlenaMata a pedido dos parceiros que não aprovaram a última proposta. 

A orientação geral de feedback é adotar um tom mais claro e adotar uma linha em volta da área. Também é preciso checar com as outras cores da camada usadas no mapa. 

Sugestão do @bwstefano : marrom (TIs) e verde (UCs). Ele pediu pra procurar manter cores que estão no InfoAmazonia e caso a @luizapeixe tenha dúvida, ela pode procurá-lo para alinhar antes de definir as novas cores/estilos.

**Comment by luizapeixe** [comment]
é fundamental que as escolhas cromáticas deste projeto sejam baseadas na identidade visual desenvolvida e aprovada para o PlenaMata. Mesmo que o projeto tenham relação editorial com o InfoAmazonia, utilizar cores de outro projeto no PlenaMata poderá deixar o elemento descontextualizado e enfraquecer a unidade estética da plataforma.

_identidade visual aprovada do PlenaMata: https://www.figma.com/proto/yvR6FM91jrnC8xwt8iUYom/Plataforma-Produ%C3%A7%C3%A3o?page-id=0%3A1&node-id=1%3A2454&viewport=241%2C48%2C0.5&scaling=min-zoom_

felizmente existem as cores Marrom e Verde na paleta cromática original do PlenaMata. Seguindo as orientações dos clientes, as novas cores aplicadas no dashboard ficariam assim:

<img width="1724" alt="Captura de Tela 2021-12-08 às 13 46 41" src="https://user-images.githubusercontent.com/6249788/145248643-a42f6d18-7072-4cfc-a98e-496e45b2552a.png">

Estado: cor #F5F1EE (Stroke 80% e Fill 15%)
Terra Indígena: cor #917864 (Stroke 80% e Fill 15%)
Unidade de conservação: cor #80CC34 (Stroke 80% e Fill 15%)

**Comment by luizapeixe** [comment]
link para visualizar o layout completo: https://www.figma.com/proto/0UAxczgF2VXExYweS5vA0D/Plataforma-(entregas)?page-id=2341%3A15852&node-id=2341%3A16151&viewport=241%2C48%2C0.17&scaling=min-zoom

**Comment by paularfurtado** [comment]
Aprovados pelo @bwstefano e @mathiasfls  no grupo de WhatsApp do projeto

**Comment by matheusgimenez** [comment]
@paularfurtado tem um bug com relação a esta funcionalidade:

- Caso um post tenha mais de um ponto de geolocalização e estes pontos sejam de estados diferentes, pode acontecer de clicar em um PIN e o mapa colorir outro estado.
