### ISSUE TITLE
[Layout] Refazer layout do tooltip de glossário, considerando um background mais claro

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#106]

**Comment by luizapeixe** [comment]
que tal assim?

<img width="523" alt="Captura de Tela 2021-12-08 às 13 28 13" src="https://user-images.githubusercontent.com/6249788/145245830-2a884455-5db2-4a93-9e64-478b60ca3423.png">

background cor #F5F1EE e textos cor #221D18

**Comment by paularfurtado** [comment]
@mathiasfls

**Comment by mathiasfls** [comment]
@paularfurtado e @luizapeixe Podemos seguir com esse layout. Equipe editorial aprovou. Obrigado @luizapeixe.

**Comment by paularfurtado** [comment]
Obrigada @mathiasfls ! @luizapeixe vc poderia por favor atualizar essa versão aprovada no figma e deixar aqui o link de cliente pra registro?

**Comment by luizapeixe** [comment]
claro! eis o link para visualizar o layout proposto e aprovado: https://www.figma.com/proto/0UAxczgF2VXExYweS5vA0D/Plataforma-(entregas)?page-id=2341%3A15852&node-id=2341%3A15853&viewport=241%2C48%2C0.17&scaling=min-zoom
