### ISSUE TITLE
[Monitor] Incluir data alimentada automaticamente pela API da Solved no painel "Informações" da legenda para indicar início e fim dos dados do Deter

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#112]
[Stefano] A meu pedido, a Solved vai incluir na API a data do primeiro dado do Deter disponível na API. Isto será inserido no JSON disponível em https://plenamata.solved.eco.br/api/deter/last_date, onde já temos a data com o último dado disponível. O objetivo é inserir no painel de "Informações" da legenda desta camada uma descrição sobre a que período os dados atualizados em tempo real do Deter, adicionados ao mapa através de uma camada WMS. Assim, teremos um texto do tipo "Os dados desta camada englobam os alertas detectados no período entre {deter_last_date} e {deter_first_date}, verificados desde a última atualização do Prodes." O texto deve ser adicionado à camada, não ao mapa. As datas precisam ser convertidas para formato amigável.

**Comment by leopiccionia** [comment]
Era algo assim?

![image](https://user-images.githubusercontent.com/9576518/153891330-981627d1-ec71-43dc-a6a5-dedb57a76c22.png)

**Comment by bwstefano** [comment]
Isso é o ideal! Ficaria ótimo assim. Em inglês, teria que trocar a posição do mês com a do dia.
