### ISSUE TITLE
[API de Reportagens] Incluir possibilidade de salvar site sem que haja post disponível no momento da inclusão

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#116]
- [x] quando o site parceiro não possui post na categoria selecionada, não é possível deixar salvo esse site com as confugurações desejadas para que futuramente (no intervalo definido) ele passe a alimentar o plenamata

- [x] não é possível alterar as configurações de um site no caso de não haver posts no momento (no preview aparecem 0 posts, mas não é possível salvar dessa maneira)

**Comment by matheusgimenez** [comment]
Corrigido! :)
