### ISSUE TITLE
[Monitor] Alterar cores no mapa que demarcam as áreas filtradas conforme layout refeito e aprovado

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#118]
Discussão sobre as cores na issue #105 

Estado: bege cor #F5F1EE (Stroke 80% e Fill 15%)
Terra Indígena: marrom cor #917864 (Stroke 80% e Fill 15%)
Unidade de conservação: verde cor #80CC34 (Stroke 80% e Fill 15%)

link para visualizar o layout completo: https://www.figma.com/proto/0UAxczgF2VXExYweS5vA0D/Plataforma-(entregas)?page-id=2341%3A15852&node-id=2341%3A16151&viewport=241%2C48%2C0.17&scaling=min-zoom

**Comment by matheusgimenez** [comment]
Troquei a cor das TIs no mapa online (dashboard/monitor), porque a cor designada no layout, no mapa online, acaba ficando escondida se for num ponto do mapa marcado por muitos pontos de desmatamento

Cor aplicada (ainda no Dev): marrom cor #917864 (Stroke 80%, Fill 36%)
