### ISSUE TITLE
[API DE REPORTAGENS] Não permitir que o botão de Save seja acionado em um intervalo menor que 5 minutos. 

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#119]
[API de REPORTAGENS] Na tela de configuração deve ser possível verificar por novas notícias nos sites. Pode ser um botão para verificar todos os sites se for mais fácil, idealmente pode tb haver um botão para verificar sites específicos. Este botão só pode ser clicado uma vez a cada 5 minutos para evitar que o plugin não vire um ataque DOS aos sites dos parceiros. INSERIR um texto próximo ao botão explicando que “Clicar no botão no intervalo menor que 5 minutos pode causar sobrecarga no site do parceiro” .

**Comment by matheusgimenez** [comment]
Bom dia!

Com relação a este ponto, resolvi dentro da lógica do salvamento do site: Quando o site for salvo num periodo menor que 5 minutos, a importação não vai acontecer imediatamente, mas sim vai entrar na lista de tarefas a serem executadas pelo sistema de agendamento do WordPress, e, caso tenha outra tarefa agendada referente ao mesmo site, somente uma ficará agendada.
