### ISSUE TITLE
[Categorias] As categorias da página de notícias estão aparecendo duplicadas na archive. 

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#122]
No painel, as categorias não estão sendo filtradas por idioma, ou seja, todas são exibidas em todos os idiomas. 

![image](https://user-images.githubusercontent.com/3427567/151553913-150840f4-bba9-41d2-b039-289ef98688f6.png)

**Comment by matheusgimenez** [comment]
Corrigido.
