### ISSUE TITLE
[Mailerlite] Investigar se é possível configurar dupla autenticação no usuário da hacklab

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#131]

**Comment by bwstefano** [comment]
Este procedimento é super simples, @estercmandrade. [Compartilho aqui vídeo que fiz para orientar](https://drive.google.com/file/d/1VDaLnrRs-RTcpLHTNJDlpsJigjHg3Xot/view?usp=sharing). [Este outro link](https://www.mailerlite.com/help/how-to-turn-on-two-factor-authentication-2fa) também mostra o passo a passo.
