### ISSUE TITLE
[Complianz][Mobile] Adicionar o botão de gerenciamento de cookies no menu hamburguer.

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#134]
No mobile, a navbar está ocultando o botão de gerenciamento de cookies.

Referência do plugin: https://complianz.io/add-a-link-to-show-the-cookie-banner/ 

Observação: é funcionamento do próprio plugin omitir este botão em resoluções menores que 768px (https://complianz.io/show-settings-button-on-mobile/)

- SOLUÇÃO aprovada: incluir a opção no menu hamburguer

**Comment by willowmagrini** [comment]
Adicionamos um item no menu "Gerenciar cookies / Manage Consent" que abre a modal de configurações de cookies
