### ISSUE TITLE
[Complianz][Mobile] Reposicionar o modal de aceite de cookies que está sob a navbar.

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#135]
No mobile, a navbar está ocultando  parte do modal. Há 3 opções de como prosseguir fazendo alterações no css: 
1 - Modal sobre a navbar.
2 - Modal antes da navbar (sobre parte da primeira faixa de cada página)
3 - Posicionar os 3 botões lado a lado - horizontalmente (não recomendamos essa ao considerar boas práticas de usabilidade). 

Aprovado: opção 2

**Comment by paularfurtado** [comment]
@mathiasfls e @bwstefano , poderiam por favor nos ajudar com a definição?

**Comment by bwstefano** [comment]
@paularfurtado, acho que pode ficar sobre a navbar, logo acima dela. Que acha, @mathiasfls?

**Comment by mathiasfls** [comment]
Tinha comentado com a @paularfurtado que preferia a 2 para não cobrir o menu, porque uma vez que aceita ele não iria ficar na tela mais, mas o 1 também pode funcionar.
Sobre esse tópico, eu achei um exemplo essa semana sobre o problema de como deixar essa janela visível no mobile após a confirmação. A Exame é tem essa lingueta (Feedback). O que vi e não estou achando mais, tinha um triângulo (como o que desenhei em azul na imagem da Exame) no canto esquerdo e funcionava bem. No lado esquerdo, não afetaria muito a UX.

![IMG_3110](https://user-images.githubusercontent.com/1654069/156788996-23548668-24f2-4b3a-ba52-d22eeb5913fd.jpg)

**Comment by bwstefano** [comment]
@mathiasfls:
> que preferia a 2 para não cobrir o menu, porque uma vez que aceita ele não iria ficar na tela mais, mas o 1 também pode funcionar.

Sim, estamos concordando. Também não acho que a navbar deva ser coberta, então votei pela opção 2. 

> eu achei um exemplo essa semana sobre como deixar essa janela visível no mobile após a confirmação.

Você está falando do botão para redefinir as configurações, certo? Se sim, não acho que ele deveria ficar adesivado e preso na tela, como esse de feedback da Exame. Acho que poderia entrar dentro do menu sanduíche.

**Comment by mathiasfls** [comment]
Sim, também não gosto da lingueta. Em compensação, esse triângulo poderia funcionar em cima do menu ou a sua sugestão. 

Sobre o posicionamento, fechamos na opção 2.

**Comment by bwstefano** [comment]
Acho que a navbar já está bem cheia de itens, por isso sugeri guardar dentro do menu sanduíche.

**Comment by mathiasfls** [comment]
@bwstefano Fechamos na  2 - Modal antes da navbar (sobre parte da primeira faixa de cada página)?

**Comment by bwstefano** [comment]
Sim, @mathiasfls

**Comment by willowmagrini** [comment]
Adicionamos o css manualmente pel aferramenta de css customizado do próprio plugin:
@media screen and (max-width: 1024px) {
    .cmplz-cookiebanner {
        transform: translateY(-60px);
    }
}
