### ISSUE TITLE
[layout] Proposta de layout para descrição da estimativa de árvores derrubadas

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#136]
Requisito: ser possível inserir qualquer link do site. 

Propostas de layout: 
- **home desk**: [https://www.figma.com/proto/yvR6FM91jrnC8xwt8iUYom/Plataforma-Produção?page-id=2157:16199&node-id=2157:25050&viewport=241,48,1&scaling=min-zoom&starting-point-node-id=2157:25050&show-proto-sidebar=1](https://www.figma.com/proto/yvR6FM91jrnC8xwt8iUYom/Plataforma-Produ%C3%A7%C3%A3o?page-id=2157%3A16199&node-id=2157%3A25050&viewport=241%2C48%2C1&scaling=min-zoom&starting-point-node-id=2157%3A25050&show-proto-sidebar=1)

- **home mobile**: [https://www.figma.com/proto/yvR6FM91jrnC8xwt8iUYom/Plataforma-Produção?page-id=2157:16199&node-id=2157:26270&viewport=241,48,1&scaling=min-zoom&starting-point-node-id=2157:25480&show-proto-sidebar=1](https://www.figma.com/proto/yvR6FM91jrnC8xwt8iUYom/Plataforma-Produ%C3%A7%C3%A3o?page-id=2157%3A16199&node-id=2157%3A26270&viewport=241%2C48%2C1&scaling=min-zoom&starting-point-node-id=2157%3A25480&show-proto-sidebar=1)

- **monitor desk:** [https://www.figma.com/proto/yvR6FM91jrnC8xwt8iUYom/Plataforma-Produção?page-id=2157:16199&node-id=2157:25480&viewport=241,48,1&scaling=min-zoom&starting-point-node-id=2157:25480&show-proto-sidebar=1](https://www.figma.com/proto/yvR6FM91jrnC8xwt8iUYom/Plataforma-Produ%C3%A7%C3%A3o?page-id=2157%3A16199&node-id=2157%3A25480&viewport=241%2C48%2C1&scaling=min-zoom&starting-point-node-id=2157%3A25480&show-proto-sidebar=1)

**Comment by paularfurtado** [comment]
@mathiasfls vc poderia validar por favor?

**Comment by mathiasfls** [comment]
@paularfurtado A equipe perguntou se não teria a possibilidade de exibir isso com o i,  conforme foi discutido. Tem muita informação textual nesse campo e estamos com medo de dificultar o leitor.

**Comment by paularfurtado** [comment]
@mathiasfls não recomendamos o uso do ícone "i" nesse caso pois ele induz o usuário ao fluxo clique > modal > clique no modal  e o recurso de modal além de trazer mais complexidade para essa alteração requer também um olhar mais criterioso de UI/UX - precisaríamos equilibrar com o restante do site, já que fazemos uso de modal para verbete de outra maneira no site.  Em nossa análise, a informação textual ali é cabível no sentido que é um descritivo do número. Considerando esses apontamentos, gostaríamos por favor que vocês realizassem uma nova análise.

**Comment by mathiasfls** [comment]
@paularfurtado Levei para a equipe. Retorno quando tiver um posicionamento deles.

**Comment by mathiasfls** [comment]
A sugestão da equipe editorial é seguir com o **i**, sem a necessidade de abertura de um modal. Ao clicar nele, será direcionado para a página do glossario/matéria que explica a metolodogia. De preferência, a edição desse link (troca, caso necessário) deve ser facilitada para o editor.

**Comment by mathiasfls** [comment]
Sugestões de icones: 

https://thenounproject.com/icon/functional-analysis-1852523/

https://thenounproject.com/icon/functional-analysis-1947158/

https://thenounproject.com/icon/methodologies-2324163/

**Comment by paularfurtado** [comment]
@mathiasfls seguem os links atualizados seguindo as orientações de nossa última reunião. Consideraremos esses links como versão final e já encadeamos na lista de tarefas para o @leopiccionia na issue #149  Se tiver alguma ressalva, por favor nos avise.

- home desk: https://www.figma.com/proto/yvR6FM91jrnC8xwt8iUYom/Plataforma-Produ%C3%A7%C3%A3o?page-id=2157%3A16199&node-id=2157%3A25050&viewport=241%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=2157%3A25050

- home mobile: https://www.figma.com/proto/yvR6FM91jrnC8xwt8iUYom/Plataforma-Produ%C3%A7%C3%A3o?page-id=2157%3A16199&node-id=2157%3A26270&viewport=241%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=2157%3A25480&show-proto-sidebar=1 (aqui temos um problema com a solução de hover pq não existe hover no mobile)

- monitor desk: https://www.figma.com/proto/yvR6FM91jrnC8xwt8iUYom/Plataforma-Produ%C3%A7%C3%A3o?page-id=2157%3A16199&node-id=2157%3A25480&viewport=241%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=2157%3A25480&show-proto-sidebar=1
