### ISSUE TITLE
[API de Reportagens] Novo post de site parceiro não foi inserido no site automaticamente

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#140]
- [x]  O novo post do site Infomazonia não foi publicado automaticamente pela ferramenta. O nome do site cadastrado é InfoAmazonia-PT e o post do Infoamazonia é o https://plenamata.eco/wp-admin/post.php?post=15668&action=edit)https://infoamazonia.org/2022/03/17/crimes-areas-protegidas-inflaram-alertas-desmatamento-fevereiro-amazonia/

Obs: em DEV funcionou.

- [x] As categorias dos posts inseridos anteriormente (em prod e dev) não estão sendo exibidas na página de notícias, nas miniaturas dos posts

![image](https://user-images.githubusercontent.com/3427567/158872612-4411fd58-f1b7-4b00-874d-b8cd36026ecc.png)

**Comment by matheusgimenez** [comment]
- [ ] Na primeira noticia exibida (que aparece com maior destaque na página) a categoria não é exibida devido a um bug no JEO Theme ou no plugin-tema que estamos utilizando neste projeto. O bug ocorre de forma que só é exibida a categoria primaria do plugin Yoast SEO. Sem este metadado, simplesmente não funciona.
Podemos corrigir de duas formas:
a) Adicionando no Plugin JEO MPS este metadado (solução mais rápida);
b) Corrigindo o bug na raiz para passar a exibir corretamente as categorias mesmo sem este metadado do Yoast, de forma a seguir o comportamento padrão do WP.

- [ ] As noticias exibidas mais abaixo, com menor destaque, não são exibidas devido a um bug no tema causado pelo mesmo motivo, mas que foi resolvido de outra forma que causou este bug:
- O PHP está retornando duas vezes a mesma categoria, uma como primaria do Yoast SEO e outra vez pelo padrão do WP. Para resolver, foi aplicado um CSS para esconder a primeira delas. Acontece que no caso dos posts do JEO MPS eles não possuem o metadado do Yoast, logo, o codigo está escondendo o primeiro e o único.
