### ISSUE TITLE
[Layout] Solução para melhoria de usabilidade dos gráficos com scroll lateral

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#141]
-> proposta de solução pro scroll lateral
mobile: https://www.figma.com/proto/yvR6FM91jrnC8xwt8iUYom/Plataforma-Produção?page-id=2157:16199&node-id=2157:26565&viewport=241,48,1&scaling=min-zoom&starting-point-node-id=2157:25480&show-proto-sidebar=1
desktop: https://www.figma.com/proto/yvR6FM91jrnC8xwt8iUYom/Plataforma-Produção?page-id=2157:16199&node-id=2157:25480&viewport=241,48,1&scaling=min-zoom&starting-point-node-id=2157:25480&show-proto-sidebar=1

**Comment by paularfurtado** [comment]
De acordo com @mathiasfls essa solução impede o editorial de fazer printscreen dos gráficos para uso em reportagens. Dessa maneira vamos investigar uma nova solução como próximo passo.

**Comment by paularfurtado** [comment]
@mathiasfls avaliamos aqui que é possível utilizar esse layout e implementar o funcionamento em que é possível mover o gráfico e a mensagem não aparece mais - o que possibilita tirar printscreen dos gráficos. Você pode seguir novamente com esse layout para validação, por favor?

**Comment by mathiasfls** [comment]
Apesar de ser uma solução esteticamente bonita, ela não resolve o problema que temos para trackpad e mouse com botões (fotos). Seria importante que essa solução fosse além de design, de UX tbm.

![trackpad2-open-notification-center-1](https://user-images.githubusercontent.com/1654069/160162948-fa90f5d1-51c8-4d49-b595-4501c1c5ad7a.png)

![79083400-ad067480-7cf3-11ea-964c-b7051694e659](https://user-images.githubusercontent.com/1654069/160162944-c379e8e9-967c-4161-8a1b-3495d8524e99.png)
