### ISSUE TITLE
[Contador] remover da fonte do Contador "DETER e deixar apenas Inpe e MapiBiomas.

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#143]

**Comment by leopiccionia** [comment]
Na home e na página do placar em tempo real, a mudança é simples.

Mas, na página do monitor, o texto cita apenas o `DETER`, não o `INPE`. A string de tradução é algo como `Source: MapBiomas based on average daily deforestation detected by DETER in %s`.

Substituo `DETER` por `INPE` ali, ou deixo como está?

**Comment by mathiasfls** [comment]
Na home, trocar na texto da direita:  **Fontes: DETER/INPE e MapBiomas** por  **Fontes: INPE e MapBiomas.**
No primeiro card do monitor trocar **Fonte: MapBiomas com base na média do desmatamento diário detectado pelo DETER/INPE em 2022.** por  **Fonte: MapBiomas com base na média do desmatamento diário detectado pelo INPE em 2022.**
