### ISSUE TITLE
[Monitor] Melhoria de usabilidade nos gráficos do Monitor - novo layout

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#147]
Layout aprovado: Issue #141

Requisitos de funcionamento: é demandado que haja com a implementação desse layout os seguintes funcionamentos:
 - Possibilidade de tirar o print dos cards sem o aviso de “arraste”
 - Possibilidade de fazer a ação ser funcional em dispositivos de trackpad (movimento com dois dedos) e mouse com botões (olhar comentários na issue #141 ) .

**Comment by paularfurtado** [comment]
@mathiasfls durante a implementação dessa issue, encontramos um caminho para implementar na própria barra de rolagem o deslize da tela, sendo que agora é possível é arrastar o gráfifo tanto pela barra quanto pelo próprio gráfico. Avaliamos que embora tenhamos pensando na solução em design, a solução da barra é anterior e era a ideal. Então optamos por implementar nesse caminho. 


![image](https://user-images.githubusercontent.com/3427567/164770537-f1fd5406-2506-4eb7-89e2-917293bd497e.png)

**Comment by leopiccionia** [comment]
Revertendo ao design previamente aprovado, devido a problemas no mobile.
