### ISSUE TITLE
Investigar se há erros na implementação do contador considerando as variações identificadas

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#152]
Relato do @mathiasfls em 28/06/22: 
A Silvia (jornalista do InfoAmazonia) está acompanhando de perto o monitor e identificou que 3 milhões de árvores derrubadas em 1 dia (Isso há algumas horas).  No fim deste dia, ela reparou que mais 1 milhão de árvores estão aparecendo como derrubadas em 6h. O valor é muito alto.

Outras variações registradas:

Valor em 27/06/22:
![image](https://user-images.githubusercontent.com/3427567/176438933-ecb24fa4-facd-4ff0-8d86-2ce566a21629.png)

Valor em 21/06/22:
![image](https://user-images.githubusercontent.com/3427567/176439080-f5a07b52-be33-40d9-a87f-3cf68aafb2dd.png)

Valor em 17/06/22
![image](https://user-images.githubusercontent.com/3427567/176439220-243081a8-47d1-4b00-81f0-cd4e7f9973e0.png)

**Comment by mathiasfls** [comment]
@leopiccionia O erro no contador já foi corrigido? Lembrando que esse contador está sendo exibido em um shopping no Rio de Janeiro. Se formos atualizar, seria melhor fazer isso antes das 10h (antes do shopping abrir).

**Comment by paularfurtado** [comment]
Refatorei a lógica comum do monitor e home no arquivo js/front/utils/estimates.js.
