### ISSUE TITLE
Post via plugin MPS não carregou as informações de imagem destacada e autor.

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#154]
Relato @mathiasfl:
Silvia achou um bug na API que entrou a matéria sem a foto. Imagem enviada. Ela quer saber se pode adicionar manualmente.
Segundo a Silvia: "Entra sem imagem, sem nome do repórter, sem tags e no meio do thumb de notícias"

Observação: Verificamos que o mesmo post foi carregado no ambiente dev, demonstrando o funcionamento da sincronização. No entanto, o post veio sem imagem destacada - mesmo que no InfoAmazonia haja a imagem. 

Ambiente DEV: https://plenamata.hacklab.com.br/

Post do InfoAmazonia: https://infoamazonia.org/2022/07/14/pl-reduz-resex-chico-mendes-acre-estimula-invasoes-e-desmatamento/

![image](https://user-images.githubusercontent.com/3427567/179238549-5ed3fc5f-cc0f-4cc7-acfd-5dabe8725077.png)

**Comment by matheusgimenez** [comment]
Explicação do bug:

Em alguns casos especificos a API do WordPress pode retornar um error na imagem destacada devido a vários cenários.
Dessa forma, construí um fallback na ultima versão do Plugin, para que, caso o objeto de imagem destacada não esteja disponível, o plugin irá verificar se existe na resposta da API o objeto do plugin Yoast SEO, caso tenha, utilizará a imagem retornada por ele.
