### ISSUE TITLE
[Posts externos] Remover a exibição de posts do Media Partner

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#160]
Esses posts não devem conter single. 

Comentário do @bwstefano : Os posts que deveriam ser apenas redirecionamentos foram incorporados como tal no sitemap. Desta forma, o Google adicionou estas páginas aos resultados de busca. Estas páginas devem desaparecer: não deveriam ser acessíveis e não deveriam estar no sitemap. Exemplos: https://plenamata.eco/2022/07/21/deter-amazonas-estado-mais-desmatado-em-2022/, https://plenamata.eco/2022/08/11/mais-de-300-milhoes-de-arvores-ja-foram-derrubadas-na-amazonia-brasileira-em-2022/, https://plenamata.eco/2022/06/21/a-geografia-dos-crimes-denunciados-por-dom-phillips-e-bruno-araujo-no-vale-do-javari/

**Comment by leopiccionia** [comment]
Apliquei essa correção diretamente no tema.
