### ISSUE TITLE
[Notícias] Inclusão de duas novas seções

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#162]
Demanda da Juliana: Precisamos de uma pequena seção com os colunistas fixos agrupados e pelo menos mais uma de "Vozes da Coalizão"

**Comment by mathiasfls** [comment]
Pessoal, terá três tipos de colunistas agora: Vozes da Coalizão, Vozes Amazônicas e Colunistas Fixos. A Ju não tem colunista nesse momento para Vozes Amazônicas, mas já é para deixar desenvolvido nessa mesma task, por favor. Evitar retrabalho. Assim, seriam três novas seções, porém só duas estariam disponíveis agora. Vide conteúdo editoriais: https://docs.google.com/presentation/d/16NbXL2_Bf8xJ_2ILlDTvU6_hEfiDdDpIksIEsr4oU_k/edit#slide=id.g129ae0d2cbc_1_0

**Comment by paularfurtado** [comment]
@mathiasfls considerando seu comentário, por favor, precisamos de seu apoio para as seguintes dúvidas: 
1 - As três seções com colunistas devem exibir a listagem  o nome e foto de colunistas ou a listagem dos posts mais recentes de cada coluna? 
2 - No caso de ser a listagem dos posts, a foto e o nome dos colunistas devem ser exibidos também nas miniaturas?
3 - Já há conteúdo ou nome e foto dos colunistas  do Vozes da Coalizão, Vozes Amazônicas ?
