### ISSUE TITLE
Fazer estilo "Big Left Quote" funcionar como era no site antigo

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/plenamata#173]
Exemplo: https://plenamata.eco/2022/08/26/desromantizar-a-amazonia-para-agir/

**Comment by estercmandrade** [comment]
Como está atualmente: 
![Captura de Tela 2023-03-15 às 11 34 06](https://user-images.githubusercontent.com/91154843/225342883-e61857f1-d321-48dd-8aab-40f394270e20.png)

Como deveria ser:
![Captura de Tela 2023-03-15 às 11 34 14](https://user-images.githubusercontent.com/91154843/225342993-9d78e52c-2980-470f-9ef6-db5cd57d5612.png)

Como deveria ser no estilo Padrão:
![Captura de Tela 2023-03-15 às 11 34 27](https://user-images.githubusercontent.com/91154843/225343193-7c673d58-9c90-4731-861a-800e2a23790b.png)
