### ISSUE TITLE
Autor dos posts deve aparecer nas listagens de posts (home, notícias e eventualmente outros) e midia partners devem aparecer diferenciados, não como autores

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/plenamata#181]
Link da thread: https://chat.hacklab.com.br/channel/plenamata?msg=v6hAGc5CgFt6WGCma

**Comment by estercmandrade** [comment]
https://chat.hacklab.com.br/channel/plenamata?msg=3TWfPTyz5miK9vtiv

**Comment by estercmandrade** [comment]
- [ ] Importar e exibir autor da publicação.
