### ISSUE TITLE
Ajustar iframe do contador

### ISSUE THREAD

**Issue by estercmandrade** [hacklabr/plenamata#193]
- [x] Alterar "area degraded" para "Area degraded".
- [x] Alterar botão "Share on social media" para "Share", "Compartilhar", "Compartir".
- [x] Na opção embed de compartilhamento,  remover texto "Campos de futebol".
- [x] Na opção embed de compartilhamento, alterar "Fonte: InfoAmazonia" para "Source: MapBiomas based on DETER/INPE data. Click here to access the explanation of the calculation method. (https://plenamata.eco/en/verbete/contador-de-arvores-derrubadas/?swcfpc=1)"

**Comment by everaldomatias** [comment]
@estercmandrade faltou apenas adicionar o link em MapBiomas, porque preciso criar uma lógica para exibir o link para cada idioma.

**Comment by everaldomatias** [comment]
@estercmandrade adicionei a frase no compartilhamento do iframe.
como a frase era muito longa, achei melhor centralizar ela.

veja se está de acordo, e enviamos para produção: https://plenamata.hacklab.com.br/
