### ISSUE TITLE
Exibir Histórias Reais de acordo com o idioma

### ISSUE THREAD

**Issue by estercmandrade** [hacklabr/plenamata#203]
- [x] Exibir Histórias Reais de acordo com o idioma

**Comment by mathiasfls** [comment]
Oi Ester,

Aqui o problema não é só exibir de acordo com o idioma. Em histórias reais, os editores vão precisar adicionar as traduções, caso não adicionem, ela não exibe o conteúdo. Precisa também existir a flexibilidade de colocar conteúdos diferentes, por exemplo, algumas das histórias reais em inglês levam para links de matérias em vez de webstory.

Está claro os requisitos?

Qualquer dúvida, me avisa.

**Comment by estercmandrade** [comment]
Está claro sim. Agradeço @mathiasfls
