### ISSUE TITLE
Ajustes Archive Notícias

### ISSUE THREAD

**Issue by estercmandrade** [hacklabr/plenamata#204]
- [x] Ocultar avatar
- [x] Exibir data abaixo de autores no formato dd/mm/aaaa
- [x] Ajustar espaçamento inferior interno dos blocos VOZES DA COALIZÃO e VOZES DA AMAZÔNIA

Em outras Notícias (último bloco)
- [x] na aba todos: exibir na etiqueta a categoria primária ou a categoria mãe se não houver.
- [x] na aba das categorias:  exibir na etiqueta a categoria primária.
- [x] Exibir data logo abaixo de autores no formato dd/mm/aaaa (em todos os cards)

**Comment by leopiccionia** [comment]
Em relação ao último item, agora exibimos a categoria mãe se for a única categoria. Se for o caso, podemos modificar para não exibir nenhuma categoria.

**Comment by estercmandrade** [comment]
> Em relação ao último item, agora exibimos a categoria mãe se for a única categoria. Se for o caso, podemos modificar para não exibir nenhuma categoria.

Perfeito!

**Comment by estercmandrade** [comment]
@leopiccionia notei que na seção OUTRAS NOTÍCIAS, ao selecionar um categoria a página é recarregada.
É possível recarregar somente a seção?

**Comment by leopiccionia** [comment]
> @leopiccionia notei que na seção OUTRAS NOTÍCIAS, ao selecionar um categoria a página é recarregada. É possível recarregar somente a seção?

Isso seria complexo. Se quisermos seguir nessa direção, podemos criar uma nova issue.
