### ISSUE TITLE
[MONITOR] Investigar porque os ícones com as notícias de Belém não são exibidos.

### ISSUE THREAD

**Issue by estercmandrade** [hacklabr/plenamata#226]
Problemas com um dos clusters de notícias no mapa do monitor. 
Quando clico no cluster de 13 notícias em Belém, os ícones para ver as notícias individuais não são exibidos.

**Comment by estercmandrade** [comment]
diagnóstico leo: 

MariaDB [wordpress]> SELECT ID, post_title, post_status FROM pm_posts WHERE ID IN (SELECT post_id FROM pm_postmeta WHERE meta_key = '_geocode_city_p' AND meta_value = 'Rio Branco'); 
+-------+----------------------------------------------------------------------------------------------+-------------+
| ID    | post_title                                                                                   | post_status |
+-------+----------------------------------------------------------------------------------------------+-------------+
| 23701 | Amaz�nia tem 10% da biodiversidade do planeta e � pe�a-chave para garantia de metas da COP15 | publish     |
| 23897 | Do seringal ao Minist�rio do Meio Ambiente pela 2� vez: conhe�a a trajet�ria de Marina Silva | publish     |
| 25748 | Do seringal ao Minist�rio do Meio Ambiente pela 2� vez: conhe�a a trajet�ria de Marina Silva | publish     |
| 25763 | Amaz�nia tem 10% da biodiversidade do planeta e � pe�a-chave para garantia de metas da COP15 | publish     |
+-------+----------------------------------------------------------------------------------------------+-------------+

**Comment by leopiccionia** [comment]
Correção subida em dev, para validação da solução.
