### ISSUE TITLE
[MONITOR] Corrigir funcionando dos checkbox no mapa do Monitor

### ISSUE THREAD

**Issue by estercmandrade** [hacklabr/plenamata#227]
"Há alguns problemas com a legenda do mapa no monitor pelo mapa.

- [x] 1. Na parte de camadas, o último item é ""Limites administrativos e rótulos de lugares"". Ele aparece desmarcado, mas os limites estão ativados. 

- [x] 2. A camada ""DETER(ago 2022 - mês atual) aparece ativada, e no mapa aparece a marcação em vermelho. Mas na caixa legenda só aparece PRODES. Quando você desmarca e remarca o item ""DETER"" na caixa camada, ai sim aparece na caixa legenda a parte do DETER"

**Comment by leopiccionia** [comment]
Reabri a issue porque ainda não publicamos o release.
