### ISSUE TITLE
Alterar permissão do usuário.

### ISSUE THREAD

**Issue by estercmandrade** [hacklabr/plenamata#239]
- [x] Mudança de permissões para ter um usuário que não seja editor mas possa visualizar matérias criadas por outras pessoas antes da publicação (tanto Plenamata, como Infoamazonia).

**Comment by leopiccionia** [comment]
Adicionei um role de Revisor (Reviewer), que pode ver posts privados, mas não tem poderes de edição.

- [x] Plenamata
- [x] InfoAmazônia

**Comment by estercmandrade** [comment]
@leopiccionia criei um ususário Reviewer, mas não consigo ver as publicações no editor, e nem as publicações rascunho no fornt-end.
