### ISSUE TITLE
Criar Readme da API do monitor 

### ISSUE THREAD

**Issue by estercmandrade** [hacklabr/plenamata#241]
Readme da API do monitor - já tem o docs, é basicamente pegar esse docs e colocar num README, formatando e melhorando.

**Comment by leopiccionia** [comment]
Vide [preview](https://github.com/hacklabr/plenamata/blob/master/API.md).

Aliás, acabei reparando que o endpoint `taxaanoestado` não funciona de acordo com o código atual. Vou verificar se a API mudou.
