### ISSUE TITLE
[Monitor] Ajustes a partir do teste de guerrilha

### ISSUE THREAD

**Issue by estercmandrade** [hacklabr/plenamata#257]
Aplicação de melhorias provenientes do teste de guerrilha.

prioridade alta:
Mudanças no filtro de período não afetam os gráficos de dados, causando frustração e confusão.
Dúvidas sobre diferenças entre os gráficos, causando compreensão incorreta e frustração.
- [x] No primeiro gráfico, aplicar filtro de período nas abas ANUAL/MENSAL/SEMANAL.
- [x] Reordenar na exibição das abas para: SEMANAL/MENSAL/ANUAL

prioridade baixa:
Gostaria de pesquisar o município (barra de pesquisa)
- [x] Orientar usuário para seleção do Estado ou exibir todos os municípios. Ex: Capixaba (AC)

Gostaria de ver com mais clareza na lista as notícias em que clicou: destacar com fundo colorido ou borda.
- [x] Ao clicar no card de uma notícia, aplicar borda 1px solid #263f30.
![Captura de Tela 2023-11-23 às 10 39 59](https://github.com/hacklabr/plenamata/assets/91154843/b139adad-84e8-4ee6-966a-19cfbfe4937b)

Gerar compartilhamento dos cards de gráficos individualmente
- [x] Gerar URL das buscas realizadas. Obs: guardar também o posicionamento do mapa.

- [x] Na legenda do mapa, criar hiperlink direcionando para site do PRODES e DETER

**Comment by mpgimenez** [comment]
No ponto quanto a seleção de municipio, fiz o seguinte funcionamento:

Ao clicar no municipio sem selecionar estado, abre o select de estados.

Fiz também a colocação da borda na noticia selecionada.

**Comment by estercmandrade** [comment]
> No ponto quanto a seleção de municipio, fiz o seguinte funcionamento:
> 
> Ao clicar no municipio sem selecionar estado, abre o select de estados.
> 
> Fiz também a colocação da borda na noticia selecionada.

@mpgimenez não estou conseguindo visualizar essas alterações.

**Comment by mpgimenez** [comment]
Feito "Gerar URL das buscas realizadas. Obs: guardar também o posicionamento do mapa."
