### ISSUE TITLE
[RODAPÉ] Incluir logo e descrição Licença (CC 4.0) no rodapé do site

### ISSUE THREAD

**Issue by estercmandrade** [hacklabr/plenamata#259]
- [x] Incluir logo e descrição Licença (CC 4.0) no rodapé do site

**Comment by mpgimenez** [comment]
@estercmandrade temos algum layout para isso?

**Comment by mpgimenez** [comment]
Fiz meio de cabeça e cheguei no seguinte resultado:

![image](https://github.com/hacklabr/plenamata/assets/127668586/75c4b63a-888d-406c-938a-edaa753eae69)

Caso haja outra expectativa ou correções me avise.

**Comment by estercmandrade** [comment]
@matheusgimenez pode deixar somente o texto "Licenciado" + LOGO.
