### ISSUE TITLE
[Artigos] Se a gente agenda a publicação de um post, o texto sai com a data do agendamento como atualização (entre parenteses)

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#31]
- [x] Testar o bug descrito pelo cliente: Se a gente agenda a publicação de um post, o texto sai com a data do agendamento como atualização (entre parenteses) e não com a data de publicação. https://plenamata.hacklab.com.br/2021/09/23/teste/

- [x] Fix. O correto é exibir somente a data do agendamento.

**Comment by bwstefano** [comment]
@paularfurtado, @leopiccionia: vocês podem criar um release do tema com este e quaisquer outros ajustes feitos desde a [versão 1.5.0.1](https://github.com/EarthJournalismNetwork/jeo-theme/releases/tag/1.5.0.1)? Se estes ajustes já estiverem contemplados neste release, podem mencioná-los na descrição do release, por favor?

**Comment by leopiccionia** [comment]
Salvo engano, essa modificação já consta na versão 1.5.0.1.

**Comment by bwstefano** [comment]
Certo, @leopiccionia. Creio que atualizar o CHANGELOG é importante. Acabei de ver que dá pra gerar automaticamente as release notes [aqui](https://github.com/EarthJournalismNetwork/jeo-theme/releases/edit/1.5.0.1) e esta modificação já aparece lá. Mas gostaria da confirmação de vocês de que esta foi a única alteração antes de salvar.

Eis o que o GitHub gera automaticamente:

> ## What's Changed
> * Improve post date rendering by @leopiccionia in https://github.com/EarthJournalismNetwork/jeo-theme/pull/487
> 
> 
> **Full Changelog**: https://github.com/EarthJournalismNetwork/jeo-theme/compare/1.5.0...1.5.0.1

**Comment by leopiccionia** [comment]
> Mas gostaria da confirmação de vocês de que esta foi a única alteração antes de salvar.

Há outras modificações, mas o GitHub só gera mensagens automáticas àquelas originárias de pull request.

Voltando de férias, podemos documentar melhor esse release.

**Comment by bwstefano** [comment]
Obrigado, @leopiccionia. É muito importante que os novos releases do tema do JEO, tanto tema quanto plugin, sejam muito bem documentados e insiram notas de versão completas. Estamos tendo problemas em outros sites decorrentes de novidades em cada versão e fica difícil para os outros desenvolvedores entenderem o que acontece se as alterações não estão todas bem documentadas. Agradeço o esforço de documentar no retorno do recesso.

(cc @willowmagrini, @paularfurtado, @brunosmartin)
