### ISSUE TITLE
[Opinião] Ajustes de texto e layout na single de artigo de opinião

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#37]
- [x] Substituir a palavra MARCADOS por TAGS
![image](https://user-images.githubusercontent.com/3427567/134189955-138c5672-5e77-459d-9a45-0b221dad74fd.png)

- [x] Ajustar o tamanho da fonte que é exibida no resumo do post dentro da single -no layout é maior

**Comment by leopiccionia** [comment]
Alterei a tradução só em produção.
