### ISSUE TITLE
Validar / otimizar o desempenho do site

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#40]
Objetivo da issue: Stefano solicitou B nesse teste: https://gtmetrix.com/

-----------------------------------------------------------------------------------------------------------------------
Padrões internos a serem avaliados se são pertinentes ao projeto em questão. 

'- [ ] Verifique se o W3C e outros plug-ins para otimização estão ativos
- [ ] Verifique o desempenho usando [lighthouse] (https://developers.google.com/web/tools/lighthouse?hl=es)

**Se tem valores específicos na proposta comercial, detalhar na issue.**
Ex: "A inspeção de todas as páginas do site é realizada com conteúdo de tamanho inferior a 1MB"

Considerações

- Pelo menos 50% na analise google
- O tempo de resposta do servidor as vezes dá a louca, mesmo com cache, com alguns picos que influenciam bastante nos resultados
- Utilizar o newspack/jeo é insustentável para performance, a quantidade de CSS / JS não usado e sobrescrito é giga
- O servidor precisa ser configurado para usar uma politica de cache de arquivos "eficiente", não consegui configurar isso pelo W3 total cache, usando um outro plugin chamado "Hummingbird", eles falam sobre uma configuração que deve ser feita no NGIX
- Exterminar o arquivo css do fontawesome dos nossos projetos, utlizar o iconify parece ser a melhor opção - além do FA ser pesado, ele ainda carrega as fontes sem usar a prop font-display fazendo com que o Lighthouse nos penalize. Eu migrei alguns icones para o Iconify, mas outros influenciam no comportamento de JSs então não consegui fazer a migração total
 - O W3 total cache não faz cache na REST API na sua versão simples, apenas na PRO: Para projetos que consomem da REST API creio que seja algo que devemos levar em conta, uma solução que eu já havia utilizado no JEO era o plugin REST cache, mas creio que seja mais performatico a centralidade dos caches em um só plugin
- O plugin "Hummingbird" é bem mais poderoso em customizações e ferramentas. Ele tem varias opções de controle super especificas (cada enqueue é separado, possibilitando um controle mais rebuscado), sem falar na compressão gzip que eles tem, eu comecei a utliza-lo e até o configurei, mas devido a recriação dos arquivos que ele faz para a compressão alguns CSSs que faziam uso de caminhos relativos acabaram quebrando, por exemplo, url(../fotinha.png) - como o diretorio em que o arquivo novo foi criado é diferente do original, icones e fontes deixam de funcionar
- Existem também outros pontos que são boa parte derivados do 2, boa parte deles relacionados a politica de desenvolvimento

**Comment by mathiasfls** [comment]
@brunosmartin @paularfurtado Conforme acordamos, seria interessante esses passos da otimização serem documentados. Vocês já têm isso disponível em algum lugar para que o @bwstefano e eu possamos ler?

**Comment by paularfurtado** [comment]
Atividades realizadas: foi ativado o recurso de cache de pagina do Cloudflare usando a funcionalidade de worker do Cloudflare e um plugin de controle de cache de páginas no WordPress.

![image](https://user-images.githubusercontent.com/3427567/165604430-772762ec-5a4d-4164-a606-577f4f600088.png)
