### ISSUE TITLE
[Boas Iniciativas] inserir na foto de abertura um lugar para legenda ou crédito. Desejável que seja o recurso de ícone de câmera, que traz o tooltip com os créditos;

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#49]

**Comment by leopiccionia** [comment]
Implementei os créditos, com o ícone da câmera. Tem que ter legenda também?

**Comment by mathiasfls** [comment]
Vou confirmar com ela, mas basicamente ela quer replicar o que tem no InfoAmazonia.

**Comment by mathiasfls** [comment]
Confirmado. "Tem que funcionar que nem funciona no header do site do InfoAmazonia - legenda/créditos, assim:  https://infoamazonia.org/2021/12/10/conflitos-no-campo-77-dos-assassinatos-em-2021-foram-na-amazonia-legal/"
