### ISSUE TITLE
[Mapa] Falta a atribuição correta do Mapbox, com logo e texto, conforme indicado em https://docs.mapbox.com/help/getting-started/attribution/

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#52]

**Comment by leopiccionia** [comment]
Após investigação, esse problema precisa ser corrigido no Jeo Plugin.

Aí precisamos pensar como conciliar isso com o texto de atribuição inserido pelo usuário:

1. Colocar o logo do Mapbox na esquerda e os links do Mapbox + links inseridos pelo usuário na direita.
2. Colocar o logo e links do Mapbox na esquerda e os links inseridos pelo usuário na direita.
3. Manter os links inseridos pelo usuário na direita e adicionar o logo e links do Mapbox no modal de informações do mapa.

**Comment by bwstefano** [comment]
@leopiccionia, a terceira não é uma opção porque estaria em desacordo com a licença do Mapbox. Da mesma página:

>  While you may move the logo to a different corner of the map, we require the Mapbox logo to appear on our maps so that Mapbox and its maps get proper credit.

[Aqui](https://docs.mapbox.com/mapbox-gl-js/api/markers/#attributioncontrol) também há uma explicação importante:

> Attribution should not be collapsed if it can comfortably fit on the map.

(cc @mathiasfls)

**Comment by matheusgimenez** [comment]
Corrigido!

Precisava marcar para Carregar Interações na camada cujo os dados/graficos são do mapbox e/ou osm.

**Comment by bwstefano** [comment]
Perfeito! Isso resolve o problema, @matheusgimenez.
