### ISSUE TITLE
[Mapa] Alterar os estilos dos contornos dos municípios e do estado quando forem selecionados nos filtros.

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#74]
Implementados filtros por estado e por TI;

**Comment by matheusgimenez** [comment]
O código está funcionando, porém, para rodar na produção/dev, preciso modificar uma das camadas do mapa dentro do studio do mapbox com a conta cadastrada no site (acredito que seja do InfoAmazonia).

@paularfurtado consegue vir isso por gentileza?

Abs!
