### ISSUE TITLE
Category Opinion erro 404

### ISSUE THREAD

**Issue by estercmandrade** [hacklabr/plenamata#88]
A página da categoria Opinion (EN) está com erro: 404
https://plenamata.eco/en/category/opinion/

**Comment by leopiccionia** [comment]
Corrigido.

Havia um redirect circular `/en/category/opinion` → `/en/category/opinions` → `/en/category/opinion` configurado no Yoast.

**Comment by paularfurtado** [comment]
Identificado problema no redirect do Yoast
