### ISSUE TITLE
[Single Colunista] Exibir todas as publicações relacionadas ao Colunista

### ISSUE THREAD

**Issue by estercmandrade** [hacklabr/plenamata#89]
Não estão sendo exibidas todas as publicações relacionadas ao Colunista.
Verificar qual regra está sendo utilizada para exibir a listagem das publicações relacionadas ao colunista.

Paulo Artaxo possui 6 publicações, mas está sendo exibido apenas 3.
Aldem Bourscheit possui 24 publicações, mas está sendo exibido apenas 18.

**Comment by paularfurtado** [comment]
Investigamos o caso e identificamos qual o caso em que aparece o bug:
https://plenamata.eco/wp-admin/post.php?post=10603&action=edit&lang=pt-br

Este post está com o campo de author em branco, e com os dois checks  preenchidos (autoria e biografia). Na visão do usuário, o autor é exibido na página na seção de biografia mas não no campo que deveria aparecer logo aabaixo do título. 

A situação é estranha pois o post "sabe" que o Paulo Artaxo é o autor uma vez que pega sua biografia para exibir no fim da página. 

Na página do colunista, não aparece este post na listagem

**Comment by leopiccionia** [comment]
> Para as publicações serem listadas na página do colunista, é necessário preencher os checks (autoria e biografia).

Isso não é suficiente. Há artigos com os dois checks (como [esse](https://plenamata.eco/2021/11/11/cop26-quem-vai-pagar-conta-adaptacao-mudancas-climaticas/)) que não são exibidos na listagem do autor atualmente, mesmo tendo os dois checks.

No entanto, se eu desativo o plugin Co-Authors Plus, eles aparecem. Estou para sugerir que, se não usarmos de facto esse plugin (há artigos assinalados a mais de um autor), talvez fosse melhor desativá-lo.

Aliás, desativei e reativei o plugin e artigos que antes não apareciam na listagem dos autores agora aparecem.

**Comment by estercmandrade** [comment]
[Esse](https://plenamata.eco/2021/11/11/cop26-quem-vai-pagar-conta-adaptacao-mudancas-climaticas/) está sendo listado na página do colunista. Não sei se foi a reativação do plugin.
Os artigos parecem estar sendo listados corretamente mesmo com o plugin Co-Authors Plus ativo.
