### ISSUE TITLE
[Glossário] Melhorias para efeitos de SEO

### ISSUE THREAD

**Issue by paularfurtado** [hacklabr/plenamata#92]
[Comentários do Stefano] Para efeitos de SEO, a archive de verbetes (home do Glossário) deveria incluir as tags relevantes de dados estruturados de FAQ.

**Comment by brunosmartin** [comment]
Do projeto executivo:
"dicionário socioambiental cujo conteúdo possa ser encontrado por meio de mecanismos de busca e que sigam as melhores práticas de SEO (como disponibilização de breadcrumbs e dados estruturados) para que sejam exibidos como respostas diretas a perguntas feitas no Google."

**Comment by leopiccionia** [comment]
Para consulta futura:

O método favorito do Google e Bing para transmissão de dados estruturados é o JSON-LD com [schema.org](https://schema.org/).

A Wikipédia usa o tipo [`Article`](https://schema.org/Article) para descrever um verbete (o Wikicionário não usa dados estruturados, até onde averiguei). Esse tipo herda de [`CreativeWork`](https://schema.org/CreativeWork), que também possui propriedades interessantes para nosso caso, como `dateCreated`, `dateModified`, `inLanguage` e `author` (no caso, o próprio Plenamata).

O dicionário Merriam-Webster usa [`DefinedTerm`](https://schema.org/DefinedTerm) para descrever um verbete e [`DefinedTermSet`](https://schema.org/DefinedTermSet) para descrever o próprio dicionário. Esses tipos são específicos para dicionários, mas eles ainda constam como _pending_, isso é, podem ser removidos no futuro.

O Google parece conseguir reconstruir uma lista de breadcrumbs a partir de outros dados estruturados, mas vi sites usando o tipo [`BreadcrumbList`](https://schema.org/BreadcrumbList).

**Comment by bwstefano** [comment]
Espero que as observações que deixei na planilha possam ajudar neste tema:

> Parte disso pode ser executado com o Yoast, mas talvez não seja possível personalizar os itens pela forma como a página foi montada. Mais detalhes podem ser conferidos em https://developers.google.com/search/docs/advanced/structured-data/faqpage, https://schema.org/FAQPage e https://yoast.com/how-to-build-an-faq-page/

**Comment by leopiccionia** [comment]
A ideia é transformar o glossário numa página FAQ ou adicionar uma página FAQ em separado?

Como o glossário têm muitos verbetes, teríamos muitas questões "O que é ___?", mesmo considerando apenas a categoria "Conceitos". 

Parece, também, que o Google está limitando o número de perguntas exibidas em [duas por página](https://searchengineland.com/google-limits-faq-rich-results-to-a-maximum-of-two-per-snippet-349739).

**Comment by bwstefano** [comment]
@leopiccionia, como o glossário tem respostas em páginas individualizadas, a ideia é transformar a [archive](https://plenamata.eco/glossario/) em um FAQ.

E não tem problema que o Google limite o número de perguntas exibidas. A ideia é que, ao buscar pelo título de um item do glossário, o usuário encontre a resposta que colocamos no PlenaMata, mais do que ver toda a listagem de termos no Google.
