### ISSUE TITLE
[API de Reportagens geolocalizada] Implementar plugin separado, como uma extensão do JEO

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/plenamata#98]
Do projeto executivo
"Como este plugin possui código aberto, propomos o desenvolvimento de uma extensão a ele que permita gerar uma API que possa ser lida pela PlenaMata para obter metadados das reportagens de sites parceiros e confiáveis. Assim, será possível inserir títulos, resumos, datas e fotos destacadas de reportagens publicadas por estes sites na plataforma."

- [x] Criar api de leitura que que extenda a api de post do wordpress adicionando  os metadados do JEO. Verificar se já vem na api de posts os metadados do JEO, pois caso venha, não é preciso alterá-la. Caso seja preciso alterar, levar em conta este guia: https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/
- [x]  Criar uma nova tela de configuração dentro do Menu do JEO
- [x] Nesta tela de configuração deve ser possível adicionar os endereços dos sites externos dos quais o site atual vai consumir a api. A funcionalidade de adicionar um site parceiro terá uma tela própria onde o usuário irá adicionar a url, uma ou mais categorias, um filtro de data opcional (onde só virão posts posteriores à essa data). Feito isso, antes de permitir ao usuário salvar, deve haver um botão "Testar configurações" que vai fazer a consulta de teste, exibir a quantidade de posts encontrados e exibir o título e data de publicaão dos 10 primeiros posts encontrados. Somente após esse retorno o usuário pode salvar as configurações e a sincronização é de fato executada.
- [ ] Nesta tela de configuração deve ser possível verificar por novas notícias nos sites. Pode ser um botão para verificar todos os sites se for mais fácil, idealmente pode tb haver um botão para verificar sites específicos. Este botão só pode ser clicado uma vez a cada 5 minutos para evitar que o plugin não vire um ataque DOS aos sites dos parceiros. INSREIR um texto próximo ao botão explicando que “Clicar no botão no intervalo menor que 5 minutos pode causar sobrecarga no site do parceiro” .
- [x] A sincronização deve criar os posts apenas com o título, resumo e metadados e usar a lógica já existente de "Media Partner" do Newspack/JEO.
- [x] Deve ser possível configurar o intervalo de verificação nos sites, mas ele deve ser sempre superior à 30 minutos.
- [x] Deve ser possível selecionar o post type que será criado e as categorias que serão aplicadas ao post
- [x] Adicionar metadados registrando de qual site o post foi criado, que ele foi criado pelo plugin e a data da sincronização
- [x] Nome do plugin: "Media Partner Posts Sync"

**Comment by brunosmartin** [comment]
Estimativa inicial feita com Leo e Matheus de 50 horas de trabalho

**Comment by paularfurtado** [comment]
@matheusgimenez a partir da revisão: 

- [ ] A categoria não está sendo salva quando cria um site. 
- [ ] a exibição do nome do veículo não está sendo exibida na lista de posts (criei a categoria Plenamata Especial no ambiente DEV para listar esses posts). 
- [ ] No preview, não está exibindo a quantidade de posts encontrados.

**Comment by paularfurtado** [comment]
- [ ] No preview: 
Condicional 1: se for menor que 10 posts, exibir:
Preview Import - Posts found: X
Condicional 2: se for maior que 10 posts, exibir:
Preview Import - Posts found: X

- [ ] Inserir botão de remover dentro da edição do novo site cadastrado

**Comment by paularfurtado** [comment]
- [ ] vallidar se o acesso está limitado a usuários administradores e editores
